---
- name: Rremove nodered distribution packages.
  apt:
    name:
      - nodered
      - node-red-update
    state: absent

- name: Install npm and nodejs packages.
  apt:
    name:
      - npm
      - gnupg
    update_cache: yes
    state: present


- name: Install gpg key for nodesource repo.
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodesource repository.
  apt_repository:
    repo: 'deb https://deb.nodesource.com/{{ nodejs_repo }} {{ ansible_distribution_release }} main'
    state: present

- name: Install nodejs.
  apt:
    name:
      - nodejs
