---

- debug:
    msg: Playbook running against {{ ansible_os_family }} release {{ ansible_distribution_release }}

- name: Include tasks for RedHat OS Family.
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Include tasks for Debian Stretch.
  include_tasks: debian-stretch.yml
  when: ansible_os_family == "Debian" and ansible_distribution_release == 'stretch'

- name: Include tasks for Debian Buster.
  include_tasks: debian.yml
  when: ansible_os_family == "Debian" and ansible_distribution_release == 'buster'

- name: Include tasks for Ubuntu Bionic.
  include_tasks: debian.yml
  when: ansible_os_family == "Debian" and ansible_distribution_release == 'bionic'


- name: Create node-red user.
  user:
    name: '{{ nodered_user }}'
    state: present
    system: true
    home: '{{ nodered_install_dir }}'

- name: Install node-red.
  npm:
    name: node-red
    version: '{{ nodered_version }}'
    state: present
    path: '{{ nodered_install_dir }}'

- name: Install node-red addons.
  npm:
    name: '{{ item.name }}'
    version: '{{ item.version | default(omit) }}'
    state: present
    path: '{{ nodered_install_dir }}'
  with_items: '{{ nodered_addons }}'

- name: Set ownership of octoprint install octoprint_install_dir.
  file:
    path: '{{ nodered_install_dir }}'
    recurse: yes
    owner: '{{ nodered_user }}'

- name: Install node-red service.
  template:
    src: nodered.service.j2
    dest: /lib/systemd/system/nodered.service
  notify: Start Node-Red
